In [11]:
import torch
import numpy as np

In [12]:
L = torch.Tensor([[1, -1], [2, 1]])
L

tensor([[ 1., -1.],
        [ 2.,  1.]])

In [21]:
X = torch.empty((3, 3)).normal_(mean=0, std=1)

for x in range(3):
    for y in range(3):
        X[x][y] = torch.empty(1).normal_(mean=0, std=1)

X

tensor([[-0.5810, -0.7339, -0.4758],
        [-0.2440,  0.2553, -1.0278],
        [ 1.3228, -0.2968,  0.1775]])

In [22]:
L = L.reshape(1, 1, 2, 2)
# bias = torch.tensor([0], dtype=torch.float32)
X = X.reshape(1, 1, 3, 3)
conv = torch.nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2, bias=False)
conv.weight = torch.nn.Parameter(L)
L_X = conv(X)

In [23]:
L_X

tensor([[[[-0.0800, -0.7752],
          [ 1.8494,  0.8669]]]], grad_fn=<ConvolutionBackward0>)

In [24]:
L_X = L_X.reshape(4)
L_X

tensor([-0.0800, -0.7752,  1.8494,  0.8669], grad_fn=<ViewBackward0>)

In [25]:
np.cov(L_X.detach().numpy()).sum()

1.3044397983669593