In [1]:
import torch

In [2]:
W_k = torch.Tensor([[1, 0], [0, 1]])
W_k

tensor([[1., 0.],
        [0., 1.]])

In [3]:
x1 = torch.Tensor([1, 0])
x2 = torch.Tensor([0, 2])
x3 = torch.Tensor([1, 2])
x4 = torch.Tensor([-1, -2])

In [4]:
k1 = x1 @ W_k
k2 = x2 @ W_k
k3 = x3 @ W_k
k4 = x4 @ W_k

In [10]:
W_q = torch.Tensor([[3, 1 / 2], [1 / 2, 1]])
W_q

tensor([[3.0000, 0.5000],
        [0.5000, 1.0000]])

In [11]:
q1 = x1 @ W_q
q2 = x2 @ W_q
q3 = x3 @ W_q
q4 = x4 @ W_q

In [12]:
q1 @ k1, q2 @ k2, q3 @ k3, q4 @ k4

(tensor(3.), tensor(4.), tensor(9.), tensor(9.))

In [13]:
q3 @ k3

tensor(9.)

In [14]:
W_q

tensor([[3.0000, 0.5000],
        [0.5000, 1.0000]])